[package]
name = "AAIS"
version = "1.0.0"
authors = ["Hebx <lord.noctx@gmail.com>"]

[addresses]
aais = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-addresses]
aais = "0xCAFE"
